apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: quay.io/grosenth/go-argocd-workshop:dev-77fd95b49ddf75c9b252fdd9eed2f4a0a90b1be4
