apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp-deployment
  labels:
    app: fastapi-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fastapi-webapp-container
          image: quay.io/grosenth/fastapi-argocd-workshop:dev-77fd95b49ddf75c9b252fdd9eed2f4a0a90b1be4
